#语言文件
Lang: zh_cn

#该服务器的名字，用于替换%server%
ThisServerName: "&e&l大厅"

#允许使用前缀发送跨服聊天
ChatPrefixEnable: true
#前缀
ChatPrefix: "!"
#是否能发送免费的跨服消息(不消耗喇叭，也不花钱)
FreeChat: false
#免费发送跨服消息的冷却时间(/秒)
ChatCoolTime: 30
#发送跨服消息的时候自动消耗背包里的喇叭(若FreeChat为true则无效)
AutoUse: true

Cost:
  Enable: true
  Money: 50
  PlayerPoint: 10
  
HornSet:
  BuyMenu: true
  #喇叭的有效时间(/秒)
  ResponTime: 30
  #喇叭冷却时间(/秒)
  HornCoolTime: 10
  
##跨服说话长度限制
LenthLimit:
  #最短
  Min: 0
  #最长
  Max: 40
  
###########################################
##############BOSS血条消息配置##############
###########################################

#使用BOSS血条消息,1.9以下请关闭这个！否则会报错
BossBar: false

#Boss血条的颜色
BossBarColor: GREEN

#Boss血条的风格
BossBarStyle: SOLID

BossBarFlags: []

#BossBar持续时间(/秒)
BossBarContinued: 6

BossBarMessage: "%server% &a&l%player% &7shout: &r%message%"


###############################################
#################ActionBar配置#################
################物品栏上方的消息###############
###############################################

#使用ActionBar消息
ActionBar: true

ActionBarMessage: "&a&l%player% : %message%"


#####################################
###########聊天栏配置################
#####################################

#使用聊天栏消息
Chat: true
ChatMessage: "&e&l*大喇叭* &a&l%player% : &r%message%"

HoverEnable: true
HoverMessages:
  - "--------------------"
  - "发送者:&a%player%"
  - "服务器:&a%server%"
  - " >>&d点击发起私聊<<"
  - "--------------------"
  
#开启@功能
ATEnable: true  
ATSound: ENTITY_EXPERIENCE_ORB_PICKUP

#允许跨服私聊
SpyChatEnable: true

##脏话屏蔽
ShieldMessages:
  - "操你妈"
  - "傻逼"
  - "干你妈"
  - "有病"
  - "你妈"
  - "他妈"
  - "脑残"
  - "操"
  - "fuck"
  - "shit"
##脏话替换的字符
ShieldReplaces: "♥"
  
#别碰他！
ConfigVersion: 1

#自动检查更新
AutoUpdateCheck: true